# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
