# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_auto_20170723_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
